# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

warnings_are_errors: false

env:
 global:
   - _R_CHECK_FORCE_SUGGESTS_: false


install:
 - yardstick (==0.0.5)
