language: r
cache: packages
warnings_are_errors: false

latex: false

before_install:
  - tlmgr install index

r:
  - oldrel
  - release
  - devel

notifications:
  email:
  on_success: change
  on_failure: change
