comment: false

coverage:
    range: 70..90
    round: up
    precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

codecov:
  token: 6f686015-93a7-427c-9311-a68ce9f7dfa5
